[build]
command = "npm run build"
publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.production.environment]
  API_URL = "https://recipe-sharing-project-be.onrender.com/api/v1"
  
